### ISSUE TITLE
Add specialization when creating a new user

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-client#105]
When creating a new user, add a specialization field.
An user should be able to filter based on the specialization field when searching for users to add to a document.

**Comment by iwontcode** [comment]
I can work on this enhancement @RaduCStefanescu 
I need to know what kind of control the specialization field should be - Dropdown or Text?
Also, I will need the backend service to accept this new field.

**Comment by RaduCStefanescu** [comment]
@iwontcode the control should be a Text for now.
The backend si being updated as part of this issue: https://github.com/code4romania/expert-consultation-api/issues/180

**Comment by aggo** [comment]
i will take this

**Comment by RaduCStefanescu** [comment]
In progress at @aggo
