### ISSUE TITLE
Add consultation period on document

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-client#106]
When a new document is added to the platform, we need to add a deadline period on that document.
Please see the below UX for more details:
https://www.figma.com/file/t9BrHVBxSgOOGi8tbqptjN/Expert-Consultation?node-id=77%3A835

**Comment by aggo** [comment]
@RaduCStefanescu I can take this.

**Comment by RaduCStefanescu** [comment]
All yours @aggo

**Comment by aggo** [comment]
As discussed with @georgebejan, will use a modal that gets open when clicking on Add Deadline.
