### ISSUE TITLE
Add comments voting

### ISSUE THREAD

**Issue by georgebejan** [code4romania/expert-consultation-client#116]
The platforms needs to allow users to vote on comments.
The UI for this should behave as follows: 
* Each user can vote only once per comment.
* A vote can be updated.
* The comment owner cannot vote on its own comment.
* A count for how many votes of each type (up/down) is shown for each comment

The backend API definition for votes can be found [here](https://api.legiinlucru.ro/swagger-ui.html#/vote-controller/)

**Comment by nicolaes** [comment]
Starting work on this.
