### ISSUE TITLE
Redirect to login when not authenticated

### ISSUE THREAD

**Issue by aggo** [code4romania/expert-consultation-client#117]
Redirect to the login page whenever someone accesses the site and is not logged in yet. Should be doable with an auth guard on all routes.

**Comment by nelutzu25** [comment]
Hello, I would like to take this issue. Is it possible?

**Comment by georgebejan** [comment]
@nelutzu25 sure. I assigned it to you

**Comment by georgebejan** [comment]
@nelutzu25 Actually I just check and this behavior is already there :) So this issue will be closed.
Feel free to pick any of the remaining open issues
