### ISSUE TITLE
Add more information on the document comment approve screen

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-client#135]
When browsing the comment approval section, we need more information about the comment that needs approval:

<img width="1317" alt="Screenshot 2020-11-05 at 10 42 29" src="https://user-images.githubusercontent.com/15039873/98218596-9c01a700-1f54-11eb-95b4-bd20d12e0ba5.png">

The table should also contain information about:
- the document for which the comment needs approval
- the document node for which the comment needs approval

**Comment by RaduCStefanescu** [comment]
This issue is linked to API issue: 

https://github.com/code4romania/expert-consultation-api/issues/201

**Comment by aggo** [comment]
taking this
