### ISSUE TITLE
[Bug] Article title is not shown in document view

### ISSUE THREAD

**Issue by nicolaes** [code4romania/expert-consultation-client#145]
Current behavior:

- (optional) Create a document (e.g. [rof_2018_pdf_1536138173.pdf](https://github.com/code4romania/expert-consultation-api/blob/develop/src/test/resources/pdf/rof_2018_pdf_1536138173.pdf))
- Go to document view from http://localhost:4200/documents
- Notice article titles are not displayed (check with API response - e.g. "Art. 52" from above PDF)

Expected behavior: article contains title if it comes from API (e.g. "Art. 52: Membrii de onoare")

<img src="https://user-images.githubusercontent.com/516929/102619250-d3af6180-4144-11eb-813e-990227fa5cd3.png" width="200"> <img src="https://user-images.githubusercontent.com/516929/102619267-d7db7f00-4144-11eb-9fed-e3832e8a0080.png" width="200">

**Comment by NichitaD** [comment]
I can take this one
