### ISSUE TITLE
View all documents in the platform

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-client#19]
As an user of the Legal Consultation platform, I want to be able to view all the documents in the platform.

![Homepage](https://user-images.githubusercontent.com/15039873/61460608-b8e92400-a977-11e9-9657-9c3ee20d4dc8.png)

**Comment by RaduCStefanescu** [comment]
In progress @ liviu dima

**Comment by georgebejan** [comment]
in progress by @georgebejan

**Comment by RaduCStefanescu** [comment]
This can be closed, as it is fixed by https://github.com/code4romania/expert-consultation-client/pull/50
