### ISSUE TITLE
Import CSV file with list of users

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-client#3]
As an admin user I want to be able to import a CSV file containing a list of users into the platform.
Frontend will upload the CSV file and receive a list of results.
The list of results can be editable by admin user.
The list of results should be POSTed to an endpoint for persisting the results.

![Adauga membri (1)](https://user-images.githubusercontent.com/15039873/58744955-b7cb5a00-83fe-11e9-9113-779b08905b5a.png)

**Comment by aggo** [comment]
In progress @aggo

**Comment by RaduCStefanescu** [comment]
#26 resolves this issue
Moving the issue to testing.

**Comment by RaduCStefanescu** [comment]
Logged a bug for this issue #48

**Comment by RaduCStefanescu** [comment]
Issue handled in #26
