### ISSUE TITLE
[Users] When viewing all users, toggle between list view and cards view is not working

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-client#35]
Currently, when viewing the list of all users, we can only view the list view. 
The cards view is not implemented or not working correctly.

**Comment by juliageek** [comment]
I will start working on this ticket

**Comment by RaduCStefanescu** [comment]
#41 issue fixed
Will move this card to testing

**Comment by RaduCStefanescu** [comment]
Currently the cards view is working, the toggle between the 2 views is working, but the list view is not displaying anything. I will open a new bug for this issue.
