### ISSUE TITLE
Import users from copy/paste from Excel file

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-client#4]
As an admin user I want to be able to import a list of users by copy pasting from excel file.

![Adauga membri (2)](https://user-images.githubusercontent.com/15039873/58744963-d6315580-83fe-11e9-87d1-7d739b395c8c.png)

**Comment by ciprianbolocan** [comment]
O sa ma ocup eu de el

**Comment by ioangrozea** [comment]
In progress by me.

**Comment by RaduCStefanescu** [comment]
In progress @ioangrozea
