### ISSUE TITLE
Incorrect content-type header on user csv upload

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-client#48]
When uploading a file containing users in CSV format, the header in the request is:

`content-type: application/json`

The endpoint for receiving the request is `/users/extract` and it only consumes `multipart/form-data`
The backend error is the following:
`2020-01-08 12:43:17.916  WARN 11302 --- [nio-8080-exec-4] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.web.HttpMediaTypeNotSupportedException: Content type 'application/json' not supported]`

**Comment by aggo** [comment]
@aggo

**Comment by RaduCStefanescu** [comment]
Fixed in #51
