### ISSUE TITLE
Users list view is not displaying the users

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-client#49]
When displaying the users list, the card view is working as expected.
<img width="1579" alt="Screenshot 2020-01-08 at 13 20 27" src="https://user-images.githubusercontent.com/15039873/71974234-a90d1700-3219-11ea-8484-3ca4bcb0f234.png">
But when switching to the list view, the users are not displayed at all.
<img width="1588" alt="Screenshot 2020-01-08 at 13 21 27" src="https://user-images.githubusercontent.com/15039873/71974276-ccd05d00-3219-11ea-8b72-2188a0b5ab16.png">

**Comment by damianr13** [comment]
It works fine for me
![Screenshot from 2020-02-29 13-55-09](https://user-images.githubusercontent.com/7912289/75606974-2575f500-5afb-11ea-9740-e25a01118447.png)

**Comment by RaduCStefanescu** [comment]
Yup, seems the list view is fixed now.
Will close this one.
