### ISSUE TITLE
Upload new document to platform

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-client#5]
As an admin user of the Legal Consultation platform I want to be able to import a new document into the platform.

Importing the document will trigger the saving of a document metadata information, the trigger of the document breakdown logic.

If the processing is succesful, the loading of the document should redirect to the view document breakdown page for the saved document.

![Incarca document](https://user-images.githubusercontent.com/15039873/58744981-1690d380-83ff-11e9-97e3-b32e88d50848.png)

**Comment by ioangrozea** [comment]
In progress by me.

**Comment by RaduCStefanescu** [comment]
In progress @ioangrozea

**Comment by RaduCStefanescu** [comment]
This is handled in #36 
Moving this one to testing.

**Comment by RaduCStefanescu** [comment]
This issue is handled in #36 and can be closed
