### ISSUE TITLE
After uploading a new csv file, the new users are not displayed

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-client#53]
After uploading a CSV file with new platform users, after a succesful upload, frontend should redirect to view all users and display the new users.

**Comment by aggo** [comment]
@aggo

**Comment by RaduCStefanescu** [comment]
Example of sample CSV file.

[users.txt](https://github.com/code4romania/expert-consultation-client/files/4268552/users.txt)

**Comment by damianr13** [comment]
I will take this one

**Comment by RaduCStefanescu** [comment]
Fixed by #55

**Comment by RaduCStefanescu** [comment]
Fixed in #55

**Comment by aniri** [comment]
@RaduCStefanescu I think we can close this one :D as #55 was merged
