### ISSUE TITLE
View document breakdown

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-client#6]
As an admin user of the platform I want to be able to view a document breakdown units.

![Doc breakdown edit](https://user-images.githubusercontent.com/15039873/58744993-3a541980-83ff-11e9-9b32-513a90916298.png)

**Comment by RaduCStefanescu** [comment]
In progress @razvanbretoiu

**Comment by RaduCStefanescu** [comment]
Hi @razvanbretoiu 
How is the development going? Can we help in any way?

**Comment by RaduCStefanescu** [comment]
As no answer received, will move this issue back in the backlog

**Comment by Daniel194** [comment]
I would like to take care of this task

**Comment by RaduCStefanescu** [comment]
Ok, it's all yours @Daniel194
