### ISSUE TITLE
Allow edit of document breakdown after upload

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-client#66]
After uploading the document to the platform, the pdf document is parsed in the backend automatically. The results are displayed as part of the document breakdown view.

Sometimes, the automatic parsing is not 100% accurate, so we should let the user edit the contents of the document breakdown. The user can:
- edit contents of the nodes
- delete nodes
- add new nodes

![Body](https://user-images.githubusercontent.com/15039873/81165120-282d1480-8f9a-11ea-816c-b4cacf452eef.png)

**Comment by DenissaR** [comment]
i'm working on it

**Comment by RaduCStefanescu** [comment]
This is fixed.
