### ISSUE TITLE
Add users to document breakdown units

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-client#7]
As an admin user I want to be able to add users to document breakdown units.

The admin user should be able to view a list of all the users in the platform, in order to select multiple contributors to the document.
Users should be added to entire documents.

![Adauga membri](https://user-images.githubusercontent.com/15039873/58745000-53f56100-83ff-11e9-9c5e-1d07f8622050.png)

**Comment by damianr13** [comment]
I will take this

**Comment by aggo** [comment]
@RaduCStefanescu Please check if this task still makes sense after the last changes with assigning a committee to a document.

**Comment by RaduCStefanescu** [comment]
@aggo yes you are right, this does not make sense any more, as we already add users to the whole document. Will close this one.
