### ISSUE TITLE
Add environment file for development

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-client#70]
As part of the automatic deployment, we are deploying the backend service on AWS Elastic Beanstalk. We need a new `environment` file for dev, that will contain the URL of this new backend and a build command that will build this environment.

**Comment by mihairinzis** [comment]
https://github.com/code4romania/expert-consultation-client/pull/71

**Comment by RaduCStefanescu** [comment]
Fixed in #71
