### ISSUE TITLE
Add comments to document breakdown unit

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-client#8]
As a user of the legal consultation platform, I want to be able to add comments to the document breakdown units I have been assigned to.

Only one level of replies will be available, replies to the original comment.

![RU - lege - integral - cu comentarii - open](https://user-images.githubusercontent.com/15039873/58745016-8f902b00-83ff-11e9-9e49-5e6d9f71da47.png)

**Comment by DenissaR** [comment]
I would like to take this issue and if it's necessary, I can also help with the backend part

**Comment by RaduCStefanescu** [comment]
Sounds good and it's all yours, but you might need to have this PR merged: https://github.com/code4romania/expert-consultation-client/pull/57
Currently I asked the original owner if he would be able to have a look on it. Will let you know.
