### ISSUE TITLE
Button issue on Management utilizatori page

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-client#87]
There is an issue with the button from the upper right hand side of the page on Management utilizatori page.

<img width="527" alt="Screenshot 2020-06-09 at 13 39 56" src="https://user-images.githubusercontent.com/15039873/84138437-e8ed5a00-aa56-11ea-8d2e-377f4fb8235d.png">

**Comment by sioan7** [comment]
Fixed in #95
