### ISSUE TITLE
Review comments of document breakdown unit

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-client#9]
As an admin of the Legal Consultation platform I want to be able to accept or reject comments posted by users on document breakdown units. 

In the Admin panel we need to build a panel where the admin can view latest comments on documents and can have a simple accept/reject button.

![RU - lege - integral - cu comentarii - open](https://user-images.githubusercontent.com/15039873/58745065-7045cd80-8400-11e9-9dee-978fb9c0cab5.png)

**Comment by aggo** [comment]
@RaduCStefanescu I think this needs more explanations as to where/what more exactly to show.
