### ISSUE TITLE
Display user name when user logged in

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/expert-consultation-client#99]
When a user is logged in, we need to show the complete username in the account section, in the top right corner of the page.

**Comment by aggo** [comment]
I will take this @RaduCStefanescu

**Comment by aggo** [comment]
https://github.com/code4romania/expert-consultation-client/pull/113 solves this

**Comment by aggo** [comment]
this was merged, please close @RaduCStefanescu
